"""Image memory: images fetched from the web or generated by a model, kept so a client reuses them instead of fetching
or generating them again. A fetched image is known by its address. A generated one is known by its content and found
again by its prompt. Whether a stored image fits a new need is the client's judgment: rewordings of one illustration's
prompt scored 0.75-0.88, while sibling illustrations (violin vs cello bow hold, C vs G chord) reached 0.93, so no
similarity threshold is safe and search only returns candidates."""
import base64
import binascii
import hashlib

from .llm import ProviderError
from .models import now
from .retrieval import url_key

SIGNATURES = {b"\x89PNG\r\n\x1a\n": "image/png", b"\xff\xd8\xff": "image/jpeg", b"GIF87a": "image/gif", b"GIF89a": "image/gif"}


def image_type(raw):
    """The type the bytes are, never the one a client claims. No SVG: it can carry scripts."""
    if raw[:4] == b"RIFF" and raw[8:12] == b"WEBP":
        return "image/webp"
    return next((mime for signature, mime in SIGNATURES.items() if raw.startswith(signature)), None)


def readable(scope):
    return ("shared",) if scope == "shared" else (scope, "shared")


class ImageMemory:
    """Metadata in `image` records (with a vector of the prompt or description), bytes in `image-data` records with
    the same key, so listings and searches never carry the images themselves."""

    def __init__(self, settings, repository, models):
        self.settings, self.repository, self.models = settings, repository, models

    async def remember(self, request):
        try:
            raw = base64.b64decode(request.data, validate=True)
        except binascii.Error as exc:
            raise ValueError("data must be base64") from exc
        mime = image_type(raw)
        if not mime:
            raise ValueError("A PNG, JPEG, WebP or GIF image is required")
        if len(raw) > self.settings.max_source_bytes:
            raise ValueError("Image too large")
        digest = hashlib.sha256(raw).hexdigest()
        image_id = url_key(request.url) if request.origin == "fetched" else digest
        key = f"{request.scope}|{image_id}"
        text = request.prompt or (f"{request.title}. {request.description}" if request.description else "")
        vector = None
        if text:
            try:
                vector = await self.models.embed(text)
            except ProviderError:
                pass  # still found by its address and in listings
        image = {"id": image_id, "scope": request.scope, "origin": request.origin, "url": request.url, "prompt": request.prompt,
                 "model": request.model, "title": request.title, "description": request.description, "metadata": request.metadata,
                 "mime_type": mime, "bytes": len(raw), "sha256": digest, "stored_at": now()}
        await self.repository.record("image-data", key, {"data": base64.b64encode(raw).decode("ascii")})
        await self.repository.record("image", key, image, vector)  # after its bytes, so a listed image can always be read
        return image

    async def find(self, scope="shared", url=None, query=None, origin=None, limit=20):
        """The image fetched from `url`, the images whose prompt or description is closest to `query` (with their
        similarity), or the latest ones; from the scope and the shared memory."""
        scopes = readable(scope)
        if url:
            found = [await self.repository.read_record("image", f"{s}|{url_key(url)}") for s in scopes]
        elif query:
            vector = await self.models.embed(query)
            # ponytail: other scopes' images share the index and can crowd these out of the top hits; filter inside the
            # index query if private scopes grow large.
            found = [{**image, "similarity": round(score, 3)} for image, score in
                     await self.repository.similar_records("image", vector, limit * 5) if image["scope"] in scopes]
        else:
            found = sorted([i for s in scopes for i in await self.repository.records("image", s + "|")],
                           key=lambda i: i["stored_at"], reverse=True)
        return [i for i in found if i and (not origin or i["origin"] == origin)][:limit]

    async def get(self, scope, image_id):
        for s in readable(scope):
            image = await self.repository.read_record("image", f"{s}|{image_id}")
            if image:
                return {**image, **(await self.repository.read_record("image-data", f"{s}|{image_id}") or {})}
        raise LookupError("Unknown image")

    async def forget(self, scope, image_id):
        key = f"{scope}|{image_id}"
        if not await self.repository.read_record("image", key):
            raise LookupError("Unknown image")
        for category in ("image", "image-data"):
            await self.repository.delete_records(category, key)
